name = "underfoot-backend"
main = "src/worker.js"
compatibility_date = "2025-09-01"

[vars]
CACHE_TTL_SECONDS = "60"
SSE_MAX_CONNECTIONS = "100"

# Secrets to set via `wrangler secret put` (do NOT commit values):
# - STONEWALKER_WEBHOOK
# - GEOAPIFY_API_KEY (optional)
# - OPENAI_API_KEY (optional)
