name: ci

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      # Prevent installation of platform-specific optional deps (e.g. rollup-darwin-*)
      NPM_CONFIG_OPTIONAL: 'false'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Upgrade npm to match engines
        # The project requests npm >= 11.5.2; the runner's bundled npm may be older.
        run: npm i -g npm@11.5.2

      - name: Install root deps
        run: npm ci --ignore-scripts --omit=optional

      # Frontend is a workspace; root `npm ci` installs workspace deps from the lockfile.
      # Avoid running a separate install inside `frontend` to keep installs deterministic
      # and avoid duplicate work.

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Spell Check
        run: npm run spell

      - name: Unit tests
        working-directory: frontend
        run: npm run test

      - name: Upload unit test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-frontend
          path: frontend/coverage

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: E2E tests (Playwright)
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:5173/labs/underfoot
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
