name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install root deps
        run: npm i --ignore-scripts

      - name: Format (Prettier)
        run: npm run format && npm run lint && npm run spellcheck

      - name: Unit tests (Vitest)
        working-directory: frontend
        run: npm run test

      - name: Upload unit test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-frontend
          path: frontend/coverage

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: E2E tests (Playwright)
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:5173/labs/underfoot
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
